version: "3"
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/hoshiin/csv-inserter:delegated
    ports:
      - 1323:1323
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: go_db
    volumes:
      - .data/postgres:/var/lib/postgresql/data/pgdata:delegated
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker_pwd
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_user_pwd
